/**
 * NOTE: This class is auto generated by the io.swagger code generator program (2.4.18).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import io.swagger.model.MessagingProducerConfig;

import javax.validation.Valid;

@javax.annotation.Generated(value = "io.io.swagger.codegen.languages.SpringCodegen", date = "2021-03-30T12:50:03.016+02:00")

@Api(value = "produce", description = "the produce API")
@RequestMapping(value = "/v1/messaging")
public interface ProduceApi {

    @ApiOperation(value = "Produce messages", nickname = "produce", notes = "", tags={ "producer", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Ok") })
    @RequestMapping(value = "/produce",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> produce(@ApiParam(value = "", required = true) @Valid @RequestBody MessagingProducerConfig producerConfig);

}
